spring:
  application:
    name: hr-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hr-auth
          uri: lb://hr-auth
          filters:
            - RemoveResponseHeader=Cookie,Set-Cookie
          predicates:
            - Path=/hr-auth/**
  main:
    web-application-type: reactive
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
