INSERT INTO TB_WORKERS (NAME, DAILY_INCOME) VALUES ('Bob', 200);
INSERT INTO TB_WORKERS (NAME, DAILY_INCOME) VALUES ('Clare', 245.20);
INSERT INTO TB_WORKERS (NAME, DAILY_INCOME) VALUES ('Zé', 399.99);
