server:
  port: ${PORT:0}
spring:
  application:
    name: hr-auth
  config:
    import: configserver:http://localhost:8888
security:
  oauth2:
    resource:
      id: bcrypt
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: "*"