spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/levimartines/curso-ms-config-server
server:
  port: 8888

